"""Shared matplotlib style for schematic figures.

Usage (from a docs/figures/make_*.py script):

    import sys, pathlib
    sys.path.insert(0, str(pathlib.Path(__file__).parent))
    from schematic_style import apply_style, C, box, arrow, panel_letter, stamp, save

    apply_style()
    fig, ax = plt.subplots(figsize=(9, 4.5))
    ...
    stamp(fig, repo="periLC-VTA", script=__file__)
    save(fig, "docs/img/setup_schematic.png")

Only numpy + matplotlib are required.
"""
from __future__ import annotations

import os
import pathlib

import matplotlib
import matplotlib.pyplot as plt
from matplotlib.patches import FancyArrowPatch, FancyBboxPatch

# Okabe-Ito colour-blind-safe palette
C = {
    "blue": "#0072B2",
    "orange": "#E69F00",
    "green": "#009E73",
    "vermilion": "#D55E00",
    "sky": "#56B4E9",
    "purple": "#CC79A7",
    "yellow": "#F0E442",
    "grey": "#999999",
    "lightgrey": "#DDDDDD",
    "black": "#000000",
    "white": "#FFFFFF",
}


def apply_style() -> None:
    matplotlib.rcParams.update(
        {
            "font.family": "DejaVu Sans",
            "font.size": 10,
            "axes.titlesize": 12,
            "axes.titleweight": "bold",
            "axes.labelsize": 10,
            "xtick.labelsize": 9,
            "ytick.labelsize": 9,
            "legend.fontsize": 9,
            "axes.spines.top": False,
            "axes.spines.right": False,
            "figure.facecolor": "white",
            "axes.facecolor": "white",
            "savefig.facecolor": "white",
            "savefig.dpi": 200,
            "figure.dpi": 100,
        }
    )


def box(ax, xy, w, h, text="", fc=C["lightgrey"], ec=C["black"], lw=1.0, fontsize=9,
        radius=0.15, weight="normal", color=None, zorder=2):
    """Rounded box with centred text. xy = lower-left corner in axes data units."""
    patch = FancyBboxPatch(
        xy, w, h, boxstyle=f"round,pad=0,rounding_size={radius}",
        fc=fc, ec=ec, lw=lw, zorder=zorder,
    )
    ax.add_patch(patch)
    if text:
        ax.text(xy[0] + w / 2, xy[1] + h / 2, text, ha="center", va="center",
                fontsize=fontsize, weight=weight, color=color or C["black"], zorder=zorder + 1)
    return patch


def arrow(ax, p0, p1, color=C["black"], lw=1.2, style="-|>", mutation_scale=14, zorder=3,
          connectionstyle="arc3,rad=0.0"):
    a = FancyArrowPatch(p0, p1, arrowstyle=style, color=color, lw=lw,
                        mutation_scale=mutation_scale, zorder=zorder,
                        connectionstyle=connectionstyle, shrinkA=2, shrinkB=2)
    ax.add_patch(a)
    return a


def panel_letter(ax, letter: str, x: float = -0.02, y: float = 1.05):
    ax.text(x, y, letter, transform=ax.transAxes, fontsize=13, weight="bold", va="bottom", ha="right")


def hide_axes(ax):
    ax.set_xticks([])
    ax.set_yticks([])
    for s in ax.spines.values():
        s.set_visible(False)


def stamp(fig, repo: str, script: str, kind: str = "schematic"):
    """Footer stamp: '<repo> · schematic · generated by docs/figures/<script>.py'."""
    name = pathlib.Path(script).name
    fig.text(0.995, 0.005, f"{repo} · {kind} · generated by docs/figures/{name}",
             ha="right", va="bottom", fontsize=7, color=C["grey"])


def save(fig, path: str, max_kb: int = 450):
    """Save PNG; if larger than max_kb, re-save at lower dpi until it fits (min 120 dpi)."""
    path = str(path)
    os.makedirs(os.path.dirname(path) or ".", exist_ok=True)
    dpi = int(matplotlib.rcParams["savefig.dpi"])
    while True:
        fig.savefig(path, dpi=dpi, bbox_inches="tight", pad_inches=0.15)
        kb = os.path.getsize(path) / 1024
        if kb <= max_kb or dpi <= 120:
            break
        dpi -= 20
    print(f"saved {path} ({kb:.0f} KB, {dpi} dpi)")
    return path
