from pathlib import Path
R=Path(__file__).resolve().parents[1]
parts={
"index.html":'''<div class="model-contract" id="oxt-sf15-training-v173"><strong>Recent cohort training before interpreting optical stimulation.</strong> Recovered the independent six-animal original Day1–22 MATLAB matrix (five provisional NAc plus VTA/305 separated). In the five candidate NAc animals, Active SRI increases from mean 1.226 on D1–3 to 2.116 on D15–20 (4/5 upward, paired P=.125); Passive PRI decreases from +0.497 to −0.413 (4/5 downward, P=.125). An earlier D12–14 endpoint yields only 3/5 increasing Active SRI (P=.625) and 5/5 decreasing Passive PRI (P=.0625). Thus learning trajectories vary by time window; the five must not automatically be called learners. These days are a training-progression description, NOT a baseline-ON/OFF manipulation estimate. The source MAT name includes 2000 but its actual N_shuffle variable is 100: do not call this a verified 2,000-shuffle analysis without reconstruction.</div><figure class="figure evidence-figure manuscript-square" id="oxt-sf15-training-fig-v173"><a class="figure-zoom" href="assets/OXT_SF15_training_SRI_PRI_v173.png" target="_blank" rel="noopener"><img src="assets/OXT_SF15_training_SRI_PRI_v173.png" loading="lazy" alt="New SF15 animal-indexed active and passive social feeding responses over 20 training days"/></a><figcaption>New five candidate NAc mice. A–B, individual animals in light gray, daily animal means and SEM shading, 3-day-smoothed mean as a guide; C–D, identical mice D1–3 versus D15–20 with mean±SEM and paired animal trajectories. Training effect is exploratory, not confirmed optical inhibition. <a href="data/SOE_OXT_SF15_training_comparisons_v172.csv">Full animal-level phase statistics</a>.</figcaption></figure>''',
"index-zh.html":'''<div class="model-contract" id="oxt-sf15-training-v173"><strong>先核实最近新队列的学习过程，再解释光抑制。</strong> 找回 6 只动物的正式 D1–22 MATLAB 矩阵，其中候选 NAc 5 只单独统计，VTA 的 305 不并入。5 只动物的 Active/SRI 从 D1–3 的 1.226 升至 D15–20 的 2.116（4/5 上升，双侧 P=.125）；Passive/PRI 从 +0.497 降至 −0.413（4/5 下降，P=.125）。但换成 D12–14，Active/SRI 仅 3/5 上升（P=.625），Passive/PRI 为 5/5 下降（P=.0625）。说明不同动物的学习时间过程并不一致，不能把所有新动物直接归为 learner。这是训练期的描述，<strong>不是光刺激 ON/OFF 效应</strong>。原 MAT 文件名带有 2000，但实际 N_shuffle 字段为 100，暂不能宣称已完成 2,000 次 shuffle 的新分析。</div><figure class="figure evidence-figure manuscript-square" id="oxt-sf15-training-fig-v173"><a class="figure-zoom" href="assets/OXT_SF15_training_SRI_PRI_v173.png" target="_blank" rel="noopener"><img src="assets/OXT_SF15_training_SRI_PRI_v173.png" loading="lazy" alt="SF15 新动物的主动和被动社会进食指数在训练前后变化"/></a><figcaption>候选 NAc 的五只新动物。A–B，淡灰线为各动物，红/青色为按日均值、SEM 阴影及三日平滑趋势；C–D，D1–3 与 D15–20 的同动物配对变化及均值±SEM。该图评估训练时间过程，不能解释为光抑制验证。<a href="data/SOE_OXT_SF15_training_comparisons_v172.csv">完整训练期统计</a>。</figcaption></figure>'''
}
tag='<figure class="figure evidence-figure manuscript-square" id="oxt-new-sf15-figure-v166">'
for name,block in parts.items():
 p=R/name;s=p.read_text(encoding="utf8")
 assert tag in s,name
 if 'id="oxt-sf15-training-v173"' not in s:
  s=s.replace(tag,block+"\n"+tag,1)
 p.write_text(s,encoding="utf8")
 print("ADDED_TRAINING",name)
