# -*- coding: utf-8 -*-
from pathlib import Path
R=Path(__file__).resolve().parents[1]
BLOCKS={
"index.html":'''<div class="model-contract" id="vta-matched-execution-outcome-v157"><strong>Independent neural readout check: social observation execution vs later outcome DA on exactly the same events.</strong> We used 695 real-Obs events (9 animals) with observed bouts lasting 0.5–10 s, observation offset at least 0.5 s before the behavioral outcome anchor, and finite DA in BOTH the true observation bout and fixed Post0–6 s period. This avoids misusing the extended synthetic ActionBout as observation duration. <strong>Animal-level difference of differences</strong> (Post minus real Obs-bout contrast): Active–Unrewarded gain <strong>+0.360 AUC/s, 9/9, exact two-sided P=.00391</strong>; Passive–Unrewarded <strong>+0.352, 8/9, P=.00781</strong>. Active–Passive phase change is not significant (P=.887). These are differences of outcome contrasts across two neural readouts, not a claim that absolute DA always increases. Sensitivity to ≥1 s separation and ≤5 s bout length preserves the result. Removing records with another event anchor within 6 s gives 610 events: Active 8/8, P=.00781; Passive 7/9, P=.01563. Animalwise nuisance-adjusted models covering demonstrator feeding, prior behavior, real bout duration, anchor separation and session time retain positive Active and Passive estimates in 9/9 (exact P=.00391 each); standardized-DA analysis agrees. <strong>Limits:</strong> selected prior-Observe + own-feeding anchors, not all possible Observe opportunities; DA execution and outcome windows have distinct behavioral baselines; this is exploratory, and outcome-specific motor/consummatory responses remain an alternative. It strengthens the temporal <em>information acquisition → evaluation</em> division; it does not alone prove credit-update or next sampling causality. <a href="docs/VTA_REAL_BOUT_TO_OUTCOME_EPOCH_AUDIT_v157.md">Methods and complete boundary checks</a> · <a href="data/VTA_matched_epoch_robustness_v157.csv">All sensitivity tests</a>.</div>
<figure id="vta-matched-execution-outcome-figure-v157" class="figure evidence-figure manuscript-square"><a class="figure-zoom" href="assets/VTA_matched_observation_vs_outcome_epoch_v157.png" target="_blank" rel="noopener"><img src="assets/VTA_matched_observation_vs_outcome_epoch_v157.png" loading="lazy" alt="Paired real social observation versus fixed outcome VTA DA on the identical events"/></a><figcaption><strong>Real-bout execution versus fixed 0–6 s outcome DA, same 695 events.</strong> A and B show animal-level Active–Unrewarded and Passive–Unrewarded outcome contrasts in both windows with paired animal trajectories and mean±SEM; C shows the animal-level increase in outcome separation; D is sensitivity to strictly separated event clocks and bout duration (red Active, cyan Passive). Independent animal is the inferential unit. <a href="data/VTA_matched_execpost_stats_v157.csv">Results table</a>.</figcaption></figure>''',
"index-zh.html":'''<div class="model-contract" id="vta-matched-execution-outcome-v157"><strong>新神经验证：用完全相同的事件，比较真实社会观察执行期与随后结果期的 DA。</strong> 仅保留真实观察持续 0.5–10 秒、观察结束至少比结果锚点早 0.5 秒、两个 DA 读出均有效的事件，共 <strong>695 个事件、9 只动物</strong>。不再把此前人为扩展的 ActionBout 当作真实观察时间。对每只动物先计算结果类别之间的 DA 差异，再比较两个时期的差异：<strong>Active－Unrewarded 在结果期相对观察期增强 +0.360 AUC/秒，9/9 同向，动物级双侧精确 P=.00391</strong>；<strong>Passive－Unrewarded 增强 +0.352，8/9 同向，P=.00781</strong>。Active－Passive 的两时期间差值无显著变化（P=.887）。这是<strong>结果类别区分能力的阶段性增强</strong>，不是声称所有 DA 绝对值都增加。提高观察结束与结果锚点的间隔至至少 1 秒、缩短观察至 5 秒以内，效应依然存在。排除结果窗口内出现下一次事件锚点的记录后，余 610 个事件：Active 为 8/8、P=.00781，Passive 为 7/9、P=.01563。在每只动物内控制示范鼠进食、先前行为、观察持续时间、锚点时间差及场次时间后，两个结果的增强均为 9/9 同向、P=.00391；动物内标准化 DA 后方向一致。<strong>解释边界：</strong>这批神经数据按社会观察和进食相关事件筛选，不是所有可供观察的机会；运动、舔舐及自身进食造成的结果期响应仍须严格检验。结果支持“获取社会信息→后续结果评价”是不同的神经过程，但不能单凭它证明 DA 教学作用或预测下一次主动观察。<a href="docs/VTA_REAL_BOUT_TO_OUTCOME_EPOCH_AUDIT_v157.md">完整方法与证据边界</a> · <a href="data/VTA_matched_epoch_robustness_v157.csv">敏感性检验数据</a>。</div>
<figure id="vta-matched-execution-outcome-figure-v157" class="figure evidence-figure manuscript-square"><a class="figure-zoom" href="assets/VTA_matched_observation_vs_outcome_epoch_v157.png" target="_blank" rel="noopener"><img src="assets/VTA_matched_observation_vs_outcome_epoch_v157.png" loading="lazy" alt="真实社会观察执行期与结果期相同事件上的 VTA 多巴胺配对结果"/></a><figcaption><strong>同一批事件的观察执行期与结果期 DA。</strong> A、B：各只动物 Active－Unrewarded、Passive－Unrewarded 在两个时期的差异，灰线为动物配对变化，柱为均值±SEM；C：每只动物结果区分能力增强；D：改变时间间隔与观察持续时间后的稳健性，红色 Active，青色 Passive。统计以动物为独立单位。<a href="data/VTA_matched_execpost_stats_v157.csv">完整结果表</a>。</figcaption></figure>'''
}
for name,block in BLOCKS.items():
 path=R/name;s=path.read_text(encoding="utf8")
 if 'id="vta-matched-execution-outcome-v157"' in s:continue
 anchor='<div class="model-contract" id="vta-outcome-source-interaction-v148">'
 assert anchor in s,name
 s=s.replace(anchor,block+"\n"+anchor,1)
 path.write_text(s,encoding="utf8")
 print("PATCHED",name)
