# -*- coding: utf-8 -*-
from pathlib import Path
R=Path(__file__).resolve().parents[1]

ZH=r'''<section class="alt" id="vta"><div class="container">
<div class="section-head"><div><div class="section-kicker">神经实现</div><h2>VTA 多巴胺沿着 SLM 的计算顺序展开：先决定是否采样社会信息，再处理采样误差，最后根据结果更新</h2></div><p>这里先保留原来的核心发现，再用 Codex 的真实行为时长读出做同问题复现，随后用原始时间过程解释这些模型效应在神经信号中何时出现、持续多久。</p></div>
<div class="section-significance"><strong>这一节的主问题 · </strong>行为模型已经提出采样策略、动作预测误差（APE）、奖励预测误差（RPE）和社会结果归因。VTA 分析检验这些计算能否按照社会学习真实发生的顺序在多巴胺中出现，并检查结论是否依赖某一种 FP→DA 量化方式。</div>

<div class="section-kicker" style="margin-top:28px">核心发现｜原来的 VTA–SLM 结果先回答“计算顺序是否正确”</div>
<div class="reader-guide"><div class="reader-step"><b>为什么做</b><span>如果 SLM 描述了真实神经计算，相关变量应出现在与其功能一致的时间位置。</span></div><div class="reader-step"><b>怎么做</b><span>分别检验结果前采样策略、中段 APE 和结果后更新，并用 Q 学习、选择惯性与灵活模型作竞争对照。</span></div><div class="reader-step"><b>结论</b><span>SLM 在三个预设时间轴均得到支持；通用 Q/RPE 主要解释结果后阶段。</span></div></div>
<div class="cards-3">
<div class="card good"><div class="metric-label">结果前：是否值得获取社会信息</div><div class="metric">采样策略</div><p>结果前 VTA 信号与 SLM 的采样策略一致，效应=.810，P=.0469；通用 Q/RPE 在这一阶段接近零。</p></div>
<div class="card info"><div class="metric-label">采样后、结果前：这次动作有多出乎预期</div><div class="metric">APE</div><p>中段 APE 与学习程度保持关系，效应=.667，P=.0416；控制选择惯性和经典 Q 误差后仍保留。</p></div>
<div class="card violet"><div class="metric-label">结果出现后：根据结果完成更新</div><div class="metric">RPE / 社会归因</div><p>结果后 RPE 得到支持，效应=.867，P=.0195；此时普通 Q/RPE 也有效，因此这一阶段单独看不足以区分完整机制。</p></div>
</div>
<figure class="figure evidence-figure manuscript-square"><a class="figure-zoom" href="assets/SOE_DA_temporal_logic_v67.png" rel="noopener" target="_blank"><picture><source media="(max-width:620px)" srcset="assets/SOE_DA_temporal_logic_v67_mobile.png"/><img alt="SLM 三阶段计算与 VTA 多巴胺时间顺序" loading="lazy" src="assets/SOE_DA_temporal_logic_v67.png"/></picture></a><figcaption><strong>原始核心结果：SLM 的三个计算阶段按正确的时间顺序出现在 VTA 多巴胺中。</strong>A，结果前采样策略；B，中段 APE；C，结果后 RPE；D，模型家族的时间轴比较。SLM 为 3/3，Q/RPE 主要只在结果后阶段得到支持。这个结果构成行为模型与 VTA 神经计算之间的主要机制桥梁。</figcaption></figure>
<div class="callout"><strong>先把原结论固定下来｜</strong>VTA 数据最有区分力的地方来自事件内部的时间顺序。结果后 RPE 本身并不特殊；真正增加机制信息的是更早出现的采样策略和 APE。</div>

<div class="section-kicker" style="margin-top:28px">关键复现｜只改变 FP→DA 的量化方式，再看原来的结果期 SLM 结论是否保留</div>
<div class="reader-guide"><div class="reader-step"><b>为什么做</b><span>确认原来的 SLM→VTA 结果没有依赖固定 0–6 秒这一种积分方式。</span></div><div class="reader-step"><b>怎么做</b><span>锁定同一批 1,371 个结果事件、9 只动物以及同一套行为参数和模型比较，只把 DA 读出换成 Codex 的真实行动片段 AUC/秒；持续时间低于 0.05 秒的近零片段排除。</span></div><div class="reader-step"><b>结论</b><span>社会结果归因和标量 RPE 的主要结构跨两种读出保留；RPE 相关效应在固定结果后窗口更强。</span></div></div>
<figure class="figure evidence-figure manuscript-square"><a class="figure-zoom" href="assets/SOE_VTA_codex_exact_replication_v96.png" rel="noopener" target="_blank"><img alt="固定结果后窗口与 Codex 真实行为时长读出对 SLM 结果期分析的复现" loading="lazy" src="assets/SOE_VTA_codex_exact_replication_v96.png"/></a><figcaption><strong>把结果期分析原样换成 Codex 的真实行为时长读出后，核心 SLM→VTA 关系仍保留。</strong>A，两种 DA 数值在每只动物中均正相关，中位 ρ=.785。B，RPE 家族在两种读出中保持相同方向，但真实行动片段的效应较弱。C，只用行为数据确定的被动结果归因在两种读出中都优于固定权重；真实行动片段中相对 0.75 和 1.0 均为 9/9 动物改善（P=.0039）。D，在两种读出中，结果向量误差加入标量 RPE 后都没有额外预测收益。</figcaption></figure>
<div class="cards-3">
<div class="card good"><div class="metric-label">最强的跨方法复现</div><div class="metric">社会归因直接迁移到 VTA</div><p>行为数据独立选出的被动结果归因，在固定结果后窗口和真实行动时长中都优于固定归因权重。同一规则无需用神经数据重新调参。</p></div>
<div class="card info"><div class="metric-label">误差表示的结论也保留</div><div class="metric">标量 RPE 更简洁</div><p>两种 DA 读出中，标量 RPE 家族都强于测试的结果向量误差；在标量 RPE 已进入模型后再加入向量项均无增益。</p></div>
<div class="card violet"><div class="metric-label">窗口改变的是灵敏度</div><div class="metric">结果后持续更新</div><p>RPE 家族在真实行动片段中方向仍保留，但固定 0–6 秒通常更强，提示结果评估和教学更新可延续到动作结束之后。</p></div>
</div>
<div class="callout"><strong>早期和中段为什么不能直接用“整个 observation bout”替代｜</strong>Codex 的完整观察片段平均值会把事件内部时间结构压平。用整段观察平均后，原来的结果前采样策略关系没有重现（6 只动物，P=.438），中段 APE×SRI 也没有重现（8 只动物，ρ=−.119，P=.779）。这说明结果期可以做严格的同事件双读出复现；结果前和中段需要保留时间定位，整个观察片段的平均值会稀释短暂计算。下面的 PSTH 因此承担一个关键任务：把模型统计量重新展开到真实时间轴。</div>

<div id="vta-psth-biological-v84">
<div class="section-kicker" style="margin-top:28px">原始时间过程｜模型告诉我们“什么变量有关”，PSTH 进一步告诉我们“信号什么时候出现”</div>
<div class="bio-logic"><strong>PSTH 的目的｜</strong>模型比较给出计算变量的预测价值，围事件时间直方图（PSTH）直接显示多巴胺的时间形状。页面上的 PSTH 曲线仅为帮助观察趋势进行轻度高斯平滑：固定时间曲线 σ=1.5 个 0.1 秒时间格，行为片段相位曲线 σ=2 个相位点；所有窗口均值、逐动物统计和 P 值都使用未平滑数据。</div>

<div class="section-kicker" style="margin-top:22px">1｜观察期：VTA 是否真的对应有效社会信息采样？</div>
<div class="reader-guide"><div class="reader-step"><b>为什么做</b><span>原来的 early-policy 结果仍可能被位置、同伴动作或普通视觉变化解释。</span></div><div class="reader-step"><b>怎么做</b><span>把真实观察与同一区域随机不观察、观察区外以及示范鼠状态转换逐一比较，并同时看固定时间和真实观察片段。</span></div><div class="reader-step"><b>结论</b><span>只有动物真正进入有效观察状态时出现稳定 VTA 上升。</span></div></div>
<figure class="figure evidence-figure manuscript-square"><a class="figure-zoom" href="assets/SOE_FP_social_sampling_specificity_v92.png" rel="noopener" target="_blank"><img alt="有效社会观察对 VTA 多巴胺的选择性招募" loading="lazy" src="assets/SOE_FP_social_sampling_specificity_v92.png"/></a><figcaption><strong>观察期 VTA 信号具有社会信息采样特异性。</strong>A，真实观察高于同一区域随机不观察，0–6 秒为 8/9 动物同方向，P=.0078。B，观察区内高于观察区外，0–2 秒和 0–6 秒均为 9/9，P=.0039。C，差异贯穿真实观察片段，8/9，P=.0078。D，示范鼠状态转换与匹配随机时刻接近。位置和同伴动作变化均不足以解释主要信号。</figcaption></figure>
<div class="callout"><strong>回到 SLM｜</strong>结果前的 VTA 活动与动物真正进入社会信息采样状态相联系。这个控制链把 early-policy 的神经意义从一般环境反应进一步收窄到有效社会采样。</div>

<div class="section-kicker" style="margin-top:22px">2｜结果期：两种 DA 读法为什么会给 RPE 不同的灵敏度？</div>
<div class="reader-guide"><div class="reader-step"><b>为什么做</b><span>双读出复现显示 RPE 方向稳定，但固定结果后窗口更强，需要直接看原始时间结构。</span></div><div class="reader-step"><b>怎么做</b><span>在同一批结果事件中比较 Active、Passive 和 Unrewarded，并分别按事件后固定时间和真实行为持续时间展开。</span></div><div class="reader-step"><b>结论</b><span>Active 更快，Passive 更持续，Unrewarded 转为负向；结果后持续部分使固定窗口对更新信号更敏感。</span></div></div>
<figure class="figure evidence-figure manuscript-square"><a class="figure-zoom" href="assets/SOE_FP_PSTH_biological_story_v82.png" rel="noopener" target="_blank"><picture><source media="(max-width:620px)" srcset="assets/SOE_FP_PSTH_biological_story_v82_mobile.png"/><img alt="不同社会结果的 VTA 多巴胺时间过程及下一次观察状态" loading="lazy" src="assets/SOE_FP_PSTH_biological_story_v82.png"/></picture></a><figcaption><strong>结果类型决定 VTA 多巴胺的时间结构。</strong>A，固定时间轴显示 Active 的快速变化、Passive 的较持续正向信号和 Unrewarded 的持续负向状态。B，按真实行为片段归一化后，这些差异仍可见，但时间权重发生变化。C–D，上一结果还会延续到下一次观察。原始时间过程解释了为什么固定结果后窗口对部分 RPE/update 项更敏感。</figcaption></figure>
<div class="callout"><strong>回到双读出结果｜</strong>真实行动时长主要读取行为执行阶段；固定结果后窗口还保留动作结束后的评估和更新。因此两种方法的方向一致，同时对 RPE 的灵敏度不同，这个差异有明确的时间结构来源。</div>

<div class="section-kicker" style="margin-top:22px">3｜跨事件记忆：这次结果形成的 VTA 状态会不会进入下一次社会观察？</div>
<div class="reader-guide"><div class="reader-step"><b>为什么做</b><span>SLM 预测当前结果会更新内部状态，并改变下一次是否继续采样社会信息。</span></div><div class="reader-step"><b>怎么做</b><span>按上一事件是 Active、Passive 或 Unrewarded 对下一次观察重新分组，同时检查观察开始前、开始后和整个真实观察片段。</span></div><div class="reader-step"><b>结论</b><span>未奖赏后的下一次观察处于更低的 VTA 状态，Active 和 Passive 后的状态更高，而且差异在下一观察开始前已经存在。</span></div></div>
<figure class="figure evidence-figure manuscript-square"><a class="figure-zoom" href="assets/SOE_FP_next_observe_memory_v83.png" rel="noopener" target="_blank"><picture><source media="(max-width:620px)" srcset="assets/SOE_FP_next_observe_memory_v83_mobile.png"/><img alt="上一结果如何延续到下一次社会观察的 VTA 多巴胺状态" loading="lazy" src="assets/SOE_FP_next_observe_memory_v83.png"/></picture></a><figcaption><strong>一次社会结果会留下跨事件的 VTA 状态，并带入下一次观察。</strong>A–B，下一次观察开始前，Active 和 Passive 后的状态已高于 Unrewarded（P=.027/.020）。C，观察开始后 0–2 秒差异继续存在（两项 P=.008）。D，在真实观察片段早期仍保持 Active/Passive 高于 Unrewarded（两项 P=.004）。</figcaption></figure>
<div class="callout"><strong>回到 SLM 闭环｜</strong>这组结果把当前结果与未来采样连起来：<strong>社会结果 → 内部 VTA 状态 → 下一次社会信息采样</strong>。它与行为层面“结果会迅速重设下一步社会信息需求”的发现形成跨事件对应。</div>

<details id="vta-psth-support-v82"><summary>展开：模型变量 PSTH、事件控制、逐事件热图和双读出辅助证据</summary><div class="detail-body">
<div class="bio-logic"><strong>这些图承担辅助作用｜</strong>模型高低分组用于把 SLM 变量映射回时间过程；事件控制排除位置、示范鼠事件和信号质量等解释；逐事件热图展示 单事件层面的异质性。它们不替代上面的整动物留出模型比较。</div>
<figure class="figure evidence-figure manuscript-square"><a class="figure-zoom" href="assets/SOE_FP_PSTH_model_variables_v88.png" rel="noopener" target="_blank"><picture><source media="(max-width:620px)" srcset="assets/SOE_FP_PSTH_model_variables_v88_mobile.png"/><img alt="按 SLM 采样策略 RPE 和更新幅度分层的 VTA PSTH" loading="lazy" src="assets/SOE_FP_PSTH_model_variables_v88.png"/></picture></a><figcaption>按采样策略、|RPE| 和更新幅度在动物内分层后显示的时间过程。用于观察模型变量对应信号出现的位置；正式机制判断仍以交叉验证模型和预设统计为准。</figcaption></figure>
<figure class="figure evidence-figure"><a class="figure-zoom" href="assets/SOE_FP_PSTH_event_controls_v90.png" rel="noopener" target="_blank"><img alt="观察和多类控制事件的 VTA PSTH" loading="lazy" src="assets/SOE_FP_PSTH_event_controls_v90.png"/></a><figcaption>完整事件控制：真实观察、随机不观察、示范鼠状态转换、示范鼠事件以及学习者自身进食。</figcaption></figure>
<figure class="figure evidence-figure manuscript-square"><a class="figure-zoom" href="assets/SOE_FP_PSTH_additional_events_v91.png" rel="noopener" target="_blank"><img alt="示范鼠事件和自身进食的固定时间与真实片段多巴胺" loading="lazy" src="assets/SOE_FP_PSTH_additional_events_v91.png"/></a><figcaption>示范鼠触发与未触发事件提供阴性控制；学习者自身进食提供阳性控制。两者同时展示固定时间和真实行为片段视角。</figcaption></figure>
<figure class="figure evidence-figure"><a class="figure-zoom" href="assets/SOE_FP_PSTH_trial_heatmaps_v82.png" rel="noopener" target="_blank"><img alt="Active Passive Unrewarded 的逐事件 VTA 热图" loading="lazy" src="assets/SOE_FP_PSTH_trial_heatmaps_v82.png"/></a><figcaption>逐事件热图保留未平滑的 trial-level 时间结构，用来核对平均曲线是否被少量事件驱动。</figcaption></figure>
<figure class="figure evidence-figure manuscript-square"><a class="figure-zoom" href="assets/SOE_FP_DA_outcome_contrasts_v85.png" rel="noopener" target="_blank"><picture><source media="(max-width:620px)" srcset="assets/SOE_FP_DA_outcome_contrasts_v85_mobile.png"/><img alt="两种 DA 读出下的 Active Passive Unrewarded 对比" loading="lazy" src="assets/SOE_FP_DA_outcome_contrasts_v85.png"/></picture></a><figcaption>同一动物内的结果类别差异在固定 0–6 秒与真实行为片段下的并排比较。</figcaption></figure>
<figure class="figure evidence-figure manuscript-square"><a class="figure-zoom" href="assets/SOE_FP_PSTH_event_selection_v86.png" rel="noopener" target="_blank"><img alt="全部事件与共同事件 PSTH 对比" loading="lazy" src="assets/SOE_FP_PSTH_event_selection_v86.png"/></a><figcaption>全部有效事件与双读出共同事件的结果 PSTH。共同事件筛选没有改变主要时间形状。</figcaption></figure>
<figure class="figure evidence-figure manuscript-square"><a class="figure-zoom" href="assets/SOE_FP_DA_cross_readout_consensus_v78.png" rel="noopener" target="_blank"><picture><source media="(max-width:620px)" srcset="assets/SOE_FP_DA_cross_readout_consensus_v78_mobile.png"/><img alt="两种 FP 到 DA 读出的逐动物一致性" loading="lazy" src="assets/SOE_FP_DA_cross_readout_consensus_v78.png"/></picture></a><figcaption>双读出的逐动物稳健性辅助图；主页面的 v96 图已把结果重新组织成 SLM 复现问题。</figcaption></figure>
</div></details>
</div>

<div class="callout"><strong>VTA 部分的整合结论｜</strong>行为数据先定义了 SLM 的计算坐标；原始 VTA 分析把采样策略、APE 和结果后更新放在正确的事件内时间位置。Codex 的真实行为时长读出进一步说明，行为中学到的社会归因和标量 RPE 结构并不依赖固定 0–6 秒这一种 DA 量化。PSTH 则解释了两种读出差异的时间来源，并显示有效社会观察与上一结果形成的内部状态会延续到下一次采样。由此得到一条连续神经计算链：<strong>决定是否观察 → 获取社会信息 → 处理采样误差 → 根据结果更新 → 改变下一次社会采样。</strong></div>

<div class="download-grid">
<div class="download-card"><a href="data/DA_global_temporal_model_adjudication_v4_authority.csv">原始 VTA 三阶段 authority</a><p>采样策略、APE、结果后更新与竞争模型的逐阶段结果。</p></div>
<div class="download-card"><a href="data/SOE_VTA_CODEX_EXACT_REPLICATION_v96.csv">Codex 双读出复现结果</a><p>同一 1,371 个结果事件上固定 0–6 秒与真实行动片段的逐项模型结果。</p></div>
<div class="download-card"><a href="data/SOE_VTA_CODEX_OBSERVATION_BOUT_MIRROR_v97.csv">完整观察片段镜像检验</a><p>完整观察片段平均会稀释结果前和中段的短暂计算。</p></div>
<div class="download-card"><a href="data/SOE_FP_SOCIAL_SAMPLING_SPECIFICITY_v92.csv">社会采样特异性</a><p>真实观察、位置匹配、观察区内外与示范鼠转换控制。</p></div>
<div class="download-card"><a href="data/SOE_FP_NEXT_OBSERVE_STATE_STATS_v83.csv">下一次观察状态</a><p>上一结果如何延续到下一观察前、后及真实观察片段。</p></div>
<div class="download-card"><a href="docs/SLM_DOPAMINE_MULTIPERSPECTIVE_AUDIT_v1_20261006.md">SLM × VTA 多角度审计</a><p>行为、神经时间轴、双读出、PSTH 与解释边界。</p></div>
</div>
</div></section>'''

EN=r'''<section class="alt" id="vta"><div class="container">
<div class="section-head"><div><div class="section-kicker">Neural implementation</div><h2>VTA dopamine unfolds in the order predicted by SLM: decide whether to sample, evaluate the sampling action, then update from the outcome</h2></div><p>The section first preserves the original VTA–SLM result, then asks whether the same outcome-stage conclusions survive the Codex real-bout FP-to-DA readout, and finally uses time-resolved PSTHs to reveal when each signal appears.</p></div>
<div class="section-significance"><strong>Main question · </strong>Behavior defines sampling policy, action prediction error (APE), reward prediction error (RPE), and social credit. The neural analysis asks whether these computations appear in VTA dopamine at the biologically appropriate times and whether the conclusion depends on one FP-to-DA quantification.</div>

<div class="section-kicker" style="margin-top:28px">Core result | The original VTA–SLM analysis first established computational order</div>
<div class="reader-guide"><div class="reader-step"><b>Why</b><span>If SLM captures the neural computation, each variable should appear at the time when it can be used.</span></div><div class="reader-step"><b>How</b><span>We separately test pre-outcome sampling policy, middle APE, and post-outcome updating against Q-learning, choice persistence and flexible alternatives.</span></div><div class="reader-step"><b>Result</b><span>SLM is supported on all three pre-specified temporal axes; generic Q/RPE is mainly supported after the outcome.</span></div></div>
<div class="cards-3">
<div class="card good"><div class="metric-label">Before outcome: is social information worth sampling?</div><div class="metric">Sampling policy</div><p>Pre-outcome VTA activity follows the SLM sampling policy (effect=.810, P=.0469), while generic Q/RPE is near zero at this stage.</p></div>
<div class="card info"><div class="metric-label">After sampling, before outcome: how unexpected was the action?</div><div class="metric">APE</div><p>Middle APE remains related to learning (effect=.667, P=.0416) after controls for choice persistence and classical Q errors.</p></div>
<div class="card violet"><div class="metric-label">After outcome: update from what happened</div><div class="metric">RPE / social credit</div><p>Post-outcome RPE is supported (effect=.867, P=.0195); generic Q/RPE also works here, so the post period alone cannot identify the full mechanism.</p></div>
</div>
<figure class="figure evidence-figure manuscript-square"><a class="figure-zoom" href="assets/SOE_DA_temporal_logic_v67.png" rel="noopener" target="_blank"><picture><source media="(max-width:620px)" srcset="assets/SOE_DA_temporal_logic_v67_mobile.png"/><img alt="Temporal order of SLM computations in VTA dopamine" loading="lazy" src="assets/SOE_DA_temporal_logic_v67.png"/></picture></a><figcaption><strong>Original core result: the three SLM computations appear in VTA dopamine in the correct temporal order.</strong>A, pre-outcome sampling policy. B, middle APE. C, post-outcome RPE. D, model-family temporal adjudication. SLM is positive on 3/3 axes; Q/RPE is mainly supported after outcome.</figcaption></figure>
<div class="callout"><strong>What the original result establishes.</strong> The discriminative information comes from within-event timing. Post-outcome RPE alone is broad; the earlier sampling-policy and APE stages provide the additional mechanistic structure.</div>

<div class="section-kicker" style="margin-top:28px">Key replication | Change only the FP-to-DA readout and repeat the outcome-stage SLM tests</div>
<div class="reader-guide"><div class="reader-step"><b>Why</b><span>Test whether the SLM-to-VTA result depends on the fixed 0–6 s integration window.</span></div><div class="reader-step"><b>How</b><span>Freeze the same behavior-derived variables and model comparisons, restrict to the same 1,371 events from 9 animals, and replace fixed 0–6 s DA with Codex strict real action-bout AUC/s; near-zero bouts &lt;0.05 s are excluded.</span></div><div class="reader-step"><b>Result</b><span>Social credit and the scalar-RPE structure survive both readouts; RPE effects are generally stronger in the fixed post-outcome window.</span></div></div>
<figure class="figure evidence-figure manuscript-square"><a class="figure-zoom" href="assets/SOE_VTA_codex_exact_replication_v96.png" rel="noopener" target="_blank"><img alt="Replication of outcome-stage SLM results using fixed and Codex real-bout dopamine readouts" loading="lazy" src="assets/SOE_VTA_codex_exact_replication_v96.png"/></a><figcaption><strong>The core outcome-stage SLM-to-VTA mapping survives the Codex real-bout readout.</strong>A, both DA measures are positively correlated within every animal (median ρ=.785). B, RPE-family effects retain the same direction but are weaker in the real-bout readout. C, behavior-selected Passive credit beats fixed weights under both readouts and reaches 9/9 animals for the real-bout comparisons (P=.0039). D, ???????? adds no benefit after scalar RPE under either readout.</figcaption></figure>
<div class="cards-3">
<div class="card good"><div class="metric-label">Strongest cross-method replication</div><div class="metric">Social credit transfers to VTA</div><p>Passive credit selected entirely from behavior outperforms fixed credit under both DA definitions, with no neural retuning.</p></div>
<div class="card info"><div class="metric-label">Error-code conclusion also survives</div><div class="metric">Scalar RPE is more parsimonious</div><p>Across both readouts, the scalar RPE family is stronger than the tested ???????? and vector terms add no benefit after scalar RPE.</p></div>
<div class="card violet"><div class="metric-label">Window choice changes sensitivity</div><div class="metric">Updating extends after action</div><p>RPE-family effects keep the same direction in the real action bout but are usually stronger in the fixed 0–6 s window, consistent with post-action evaluation and teaching.</p></div>
</div>
<div class="callout"><strong>Why whole-observation-bout averaging cannot replace the early/middle analyses.</strong> Averaging the entire observation bout removes temporal localization. The old early-policy relationship is not recovered by the whole-bout readout (6 animals, P=.438), and the 中段 APE×SRI relationship is also lost (8 animals, ρ=−.119, P=.779). Outcome-stage tests permit a strict same-event dual-readout replication; early and middle computations require time-resolved localization.</div>

<div id="vta-psth-biological-v84">
<div class="section-kicker" style="margin-top:28px">Raw time course | Models say which computation matters; PSTHs show when the neural signal appears</div>
<div class="bio-logic"><strong>Display convention.</strong> PSTH curves are lightly Gaussian-smoothed only for visualizing trends: σ=1.5 bins for 0.1-s fixed-time curves and σ=2 phase points for bout-normalized curves. All window averages, animal-level tests and P values use the unsmoothed data.</div>

<div class="section-kicker" style="margin-top:22px">1 | Observation: is VTA specifically recruited during effective social sampling?</div>
<div class="reader-guide"><div class="reader-step"><b>Why</b><span>The early-policy result could otherwise reflect location, partner motion, or generic visual events.</span></div><div class="reader-step"><b>How</b><span>Compare real observation with random no-observation moments in the same zone, outside-zone observation, and demonstrator transitions, using fixed time and real observation-bout phase.</span></div><div class="reader-step"><b>Result</b><span>Stable VTA recruitment appears when the learner actually enters the effective observation state.</span></div></div>
<figure class="figure evidence-figure manuscript-square"><a class="figure-zoom" href="assets/SOE_FP_social_sampling_specificity_v92.png" rel="noopener" target="_blank"><img alt="Specific recruitment of VTA dopamine during effective social observation" loading="lazy" src="assets/SOE_FP_social_sampling_specificity_v92.png"/></a><figcaption><strong>The observation-period VTA signal is specific to effective social sampling.</strong>A, real observation exceeds random no-observation moments in the same zone (8/9 over 0–6 s, P=.0078). B, inside exceeds outside observation (9/9, P=.0039). C, the difference persists across the real observation bout (8/9, P=.0078). D, demonstrator transitions do not reproduce the signal.</figcaption></figure>
<div class="callout"><strong>Back to SLM.</strong> Pre-outcome VTA activity is tied to entry into a genuine social-information-sampling state, narrowing the biological interpretation of the early-policy result.</div>

<div class="section-kicker" style="margin-top:22px">2 | Outcome: why do the two DA readouts differ in RPE sensitivity?</div>
<div class="reader-guide"><div class="reader-step"><b>Why</b><span>The dual-readout replication preserves RPE direction but shows stronger evidence in the fixed post-outcome window.</span></div><div class="reader-step"><b>How</b><span>Compare Active, Passive and Unrewarded outcomes on the same events in fixed time and real bout phase.</span></div><div class="reader-step"><b>Result</b><span>Active is faster, Passive is more sustained, and Unrewarded becomes negative; post-action activity boosts the fixed-window update signal.</span></div></div>
<figure class="figure evidence-figure manuscript-square"><a class="figure-zoom" href="assets/SOE_FP_PSTH_biological_story_v82.png" rel="noopener" target="_blank"><picture><source media="(max-width:620px)" srcset="assets/SOE_FP_PSTH_biological_story_v82_mobile.png"/><img alt="Outcome-specific VTA dopamine time courses and the next-observation state" loading="lazy" src="assets/SOE_FP_PSTH_biological_story_v82.png"/></picture></a><figcaption><strong>Outcome identity shapes the temporal structure of VTA dopamine.</strong>A, fixed time reveals a fast Active response, a more sustained Passive response, and persistent negative Unrewarded activity. B, real-bout normalization preserves the separation with different temporal weighting. C–D, the previous outcome also persists into the next observation.</figcaption></figure>
<div class="callout"><strong>Back to the dual-readout result.</strong> Real-bout DA emphasizes execution; fixed post-outcome DA also retains evaluation and updating after the behavior ends. This explains why the direction is shared while RPE sensitivity differs.</div>

<div class="section-kicker" style="margin-top:22px">3 | Cross-event memory: does the VTA state created by one outcome enter the next observation?</div>
<div class="reader-guide"><div class="reader-step"><b>Why</b><span>SLM predicts that an outcome updates internal state and changes subsequent social sampling.</span></div><div class="reader-step"><b>How</b><span>Condition the next observation on whether the preceding outcome was Active, Passive or Unrewarded, and examine the period before observation, immediately after onset, and across the real bout.</span></div><div class="reader-step"><b>Result</b><span>The next observation is already in a lower VTA state after Unrewarded, while Active and Passive leave a higher state.</span></div></div>
<figure class="figure evidence-figure manuscript-square"><a class="figure-zoom" href="assets/SOE_FP_next_observe_memory_v83.png" rel="noopener" target="_blank"><picture><source media="(max-width:620px)" srcset="assets/SOE_FP_next_observe_memory_v83_mobile.png"/><img alt="Previous outcome persists into the next social observation in VTA dopamine" loading="lazy" src="assets/SOE_FP_next_observe_memory_v83.png"/></picture></a><figcaption><strong>A social outcome leaves a cross-event VTA state that carries into the next observation.</strong>A–B, before the next observation starts, Active and Passive histories already exceed Unrewarded (P=.027/.020). C, the difference persists over 0–2 s after observation begins (both P=.008). D, it remains in the early phase of the real observation bout (both P=.004).</figcaption></figure>
<div class="callout"><strong>Back to the SLM loop.</strong> The neural sequence now connects <strong>social outcome → internal VTA state → next social-information sample</strong>, matching the behavioral finding that outcomes rapidly reset the need for further social information.</div>

<details id="vta-psth-support-v82"><summary>Expand: model-stratified PSTHs, event controls, trial heatmaps and dual-readout supporting analyses</summary><div class="detail-body">
<div class="bio-logic"><strong>Role of these panels.</strong> Model stratification visualizes where SLM variables sit in time; event controls rule out simpler explanations; heatmaps retain trial-level heterogeneity. Primary mechanistic inference remains anchored to held-animal model comparisons and pre-specified statistics.</div>
<figure class="figure evidence-figure manuscript-square"><a class="figure-zoom" href="assets/SOE_FP_PSTH_model_variables_v88.png" rel="noopener" target="_blank"><picture><source media="(max-width:620px)" srcset="assets/SOE_FP_PSTH_model_variables_v88_mobile.png"/><img alt="VTA PSTHs stratified by SLM policy RPE and update magnitude" loading="lazy" src="assets/SOE_FP_PSTH_model_variables_v88.png"/></picture></a><figcaption>Within-animal stratification by sampling policy, |RPE| and update magnitude, used to visualize temporal placement rather than as the primary inferential test.</figcaption></figure>
<figure class="figure evidence-figure"><a class="figure-zoom" href="assets/SOE_FP_PSTH_event_controls_v90.png" rel="noopener" target="_blank"><img alt="VTA PSTHs for observation and control events" loading="lazy" src="assets/SOE_FP_PSTH_event_controls_v90.png"/></a><figcaption>Full event controls: real observation, random no-observation, demonstrator transitions, demonstrator events and the learner's own feeding.</figcaption></figure>
<figure class="figure evidence-figure manuscript-square"><a class="figure-zoom" href="assets/SOE_FP_PSTH_additional_events_v91.png" rel="noopener" target="_blank"><img alt="Fixed-time and real-bout VTA dopamine for demonstrator events and own feeding" loading="lazy" src="assets/SOE_FP_PSTH_additional_events_v91.png"/></a><figcaption>Triggered/untriggered demonstrator events provide a negative control; the learner's own feeding provides a positive control.</figcaption></figure>
<figure class="figure evidence-figure"><a class="figure-zoom" href="assets/SOE_FP_PSTH_trial_heatmaps_v82.png" rel="noopener" target="_blank"><img alt="Trial-level VTA heatmaps for Active Passive and Unrewarded outcomes" loading="lazy" src="assets/SOE_FP_PSTH_trial_heatmaps_v82.png"/></a><figcaption>Unsmoothed trial-level heatmaps check that the mean time courses are not produced by a small subset of events.</figcaption></figure>
<figure class="figure evidence-figure manuscript-square"><a class="figure-zoom" href="assets/SOE_FP_DA_outcome_contrasts_v85.png" rel="noopener" target="_blank"><picture><source media="(max-width:620px)" srcset="assets/SOE_FP_DA_outcome_contrasts_v85_mobile.png"/><img alt="Outcome contrasts under the two VTA dopamine readouts" loading="lazy" src="assets/SOE_FP_DA_outcome_contrasts_v85.png"/></picture></a><figcaption>Within-animal outcome contrasts under fixed 0–6 s and real-bout DA.</figcaption></figure>
<figure class="figure evidence-figure manuscript-square"><a class="figure-zoom" href="assets/SOE_FP_PSTH_event_selection_v86.png" rel="noopener" target="_blank"><img alt="All-event and common-event VTA PSTHs" loading="lazy" src="assets/SOE_FP_PSTH_event_selection_v86.png"/></a><figcaption>All valid events versus the dual-readout common-event subset; the main temporal shapes are preserved.</figcaption></figure>
<figure class="figure evidence-figure manuscript-square"><a class="figure-zoom" href="assets/SOE_FP_DA_cross_readout_consensus_v78.png" rel="noopener" target="_blank"><picture><source media="(max-width:620px)" srcset="assets/SOE_FP_DA_cross_readout_consensus_v78_mobile.png"/><img alt="Animal-level agreement between two FP-to-DA readouts" loading="lazy" src="assets/SOE_FP_DA_cross_readout_consensus_v78.png"/></picture></a><figcaption>Animal-level robustness of the two readouts; the v96 primary figure above reorganizes these results around the SLM replication question.</figcaption></figure>
</div></details>
</div>

<div class="callout"><strong>Integrated VTA conclusion.</strong> Behavior first defines the SLM coordinates; the original VTA analysis places policy, APE and post-outcome updating at the correct within-event times. The Codex real-bout readout independently preserves behavior-derived social credit and the scalar-RPE structure, showing that these mappings are not artifacts of the fixed 0–6 s definition. PSTHs reveal why sensitivity differs across readouts and show that effective social observation and outcome history shape a VTA state that carries into future sampling. The resulting neural sequence is <strong>decide whether to observe → acquire social information → evaluate the sampling action → update from the outcome → alter the next social sample.</strong></div>

<div class="download-grid">
<div class="download-card"><a href="data/DA_global_temporal_model_adjudication_v4_authority.csv">Original VTA temporal authority</a><p>Sampling policy, APE, post-outcome updating and model-family controls.</p></div>
<div class="download-card"><a href="data/SOE_VTA_CODEX_EXACT_REPLICATION_v96.csv">Codex dual-readout replication</a><p>Matched outcome-stage model tests on the same 1,371 events.</p></div>
<div class="download-card"><a href="data/SOE_VTA_CODEX_OBSERVATION_BOUT_MIRROR_v97.csv">Whole-observation-bout mirror</a><p>Shows dilution of temporally localized early/middle computations by ????????.</p></div>
<div class="download-card"><a href="data/SOE_FP_SOCIAL_SAMPLING_SPECIFICITY_v92.csv">Social-sampling specificity</a><p>Real observation, location-matched controls, inside/outside observation and demonstrator transitions.</p></div>
<div class="download-card"><a href="data/SOE_FP_NEXT_OBSERVE_STATE_STATS_v83.csv">Next-observation state</a><p>How the preceding outcome persists before, after and across the next observation bout.</p></div>
<div class="download-card"><a href="docs/SLM_DOPAMINE_MULTIPERSPECTIVE_AUDIT_v1_20261006.md">SLM × VTA audit</a><p>Behavior, neural timing, dual readouts, PSTHs and interpretation boundaries.</p></div>
</div>
</div></section>'''

def replace_section(fn,new):
    p=R/fn
    s=p.read_text(encoding="utf-8")
    k=s.find('id="vta"')
    if k<0: raise RuntimeError("VTA missing "+fn)
    a=s.rfind("<section",0,k)
    b=s.find("<section",k+1)
    if a<0 or b<0: raise RuntimeError("bounds "+fn)
    s=s[:a]+new+s[b:]
    p.write_text(s,encoding="utf-8")

replace_section("index-zh.html",ZH)
replace_section("index.html",EN)
print("VTA section rebuilt v98")
