# -*- coding: utf-8 -*-
from pathlib import Path

R=Path(__file__).resolve().parents[1]

def inject(fn,anchor,block):
    p=R/fn
    s=p.read_text(encoding="utf-8")
    if "vta-signal-zoo-v105" in s:
        print(fn,"already patched")
        return
    if anchor not in s:
        raise RuntimeError("anchor missing: "+fn)
    s=s.replace(anchor,anchor+"\n"+block,1)
    p.write_text(s,encoding="utf-8")
    print("patched",fn)

EN='''<div class="model-contract" id="vta-signal-zoo-v105"><strong>Why the behavioral model zoo becomes a VTA signal zoo.</strong> The behavioral section compares complete systems for predicting Observe. The neural section freezes computational readouts generated by those systems and asks where they appear on prespecified Early, Middle and Post axes. A family can explain Post dopamine while failing the earlier axes; therefore a successful post-outcome RPE fit does not by itself replace the full SLM sequence.</div>
<details><summary>Full VTA signal zoo (fixed temporal axes)</summary><div class="detail-body">
<p class="small">Rows are candidate computational-signal families, not a second leaderboard of complete behavioral agents. Effect definitions follow the frozen axis-specific authority: Early tests policy-linked prediction gain, Middle tests learner-linked APE/error coupling, and Post tests outcome-stage prediction gain.</p>
<div class="table-wrap"><table class="metric-table"><thead><tr><th>Candidate family</th><th>Early</th><th>Middle</th><th>Post</th><th>Positive &amp; significant</th></tr></thead><tbody>
<tr><td>SLM</td><td>+0.810 · P=.0469</td><td>+0.667 · P=.0416</td><td>+0.867 · P=.0195</td><td>3/3</td></tr>
<tr><td>Choice kernel</td><td>−0.238 · P=.688</td><td>−0.286 · P=.769</td><td>+0.467 · P=.250</td><td>0/3</td></tr>
<tr><td>TinyRNN</td><td>−0.867 · P=.0195</td><td>−0.548 · P=.924</td><td>+0.733 · P=.0547</td><td>0/3</td></tr>
<tr><td>History MLP</td><td>−0.378 · P=.359</td><td>+0.024 · P=.488</td><td>−0.911 · P=.0117</td><td>0/3</td></tr>
<tr><td>Q-all</td><td>+0.048 · P=1.000</td><td>−0.357 · P=.820</td><td>+0.867 · P=.0195</td><td>1/3</td></tr>
<tr><td>Q + choice kernel</td><td>−0.333 · P=.562</td><td>−0.333 · P=.805</td><td>+0.467 · P=.250</td><td>0/3</td></tr>
</tbody></table></div>
<p class="small"><a href="data/DA_global_temporal_model_adjudication_v4_authority.csv">Frozen temporal authority CSV</a>. TinyRNN and History MLP are flexible capacity comparators; Q-all and choice-kernel rows test classical value/persistence alternatives.</p>
</div></details>'''

ZH='''<div class="model-contract" id="vta-signal-zoo-v105"><strong>为什么行为模型库到了 VTA 变成“候选计算信号库”｜</strong>行为部分比较完整系统预测“是否观察”的能力；神经部分冻结这些系统产生的计算量，再检验它们分别出现在预设的早期、中段和结果后时间轴上的程度。某一模型家族可以解释结果期多巴胺，同时在更早时间轴缺乏支持。因此结果期 RPE 有效，只说明结果更新家族能解释这一阶段；覆盖完整社会学习链还需要早期采样策略和中段 APE。</div>
<details><summary>完整 VTA 候选信号库（固定时间轴）</summary><div class="detail-body">
<p class="small">这里每一行代表候选计算信号家族，和上方“完整行为系统预测排名”属于不同问题。效应量沿冻结的时间轴定义读取：早期检验采样策略相关预测增益，中段检验与学习强度相关的 APE/误差耦合，结果后检验结果期预测增益。</p>
<div class="table-wrap"><table class="metric-table"><thead><tr><th>候选信号家族</th><th>早期</th><th>中段</th><th>结果后</th><th>正向且显著</th></tr></thead><tbody>
<tr><td>SLM</td><td>+0.810 · P=.0469</td><td>+0.667 · P=.0416</td><td>+0.867 · P=.0195</td><td>3/3</td></tr>
<tr><td>选择惯性</td><td>−0.238 · P=.688</td><td>−0.286 · P=.769</td><td>+0.467 · P=.250</td><td>0/3</td></tr>
<tr><td>TinyRNN</td><td>−0.867 · P=.0195</td><td>−0.548 · P=.924</td><td>+0.733 · P=.0547</td><td>0/3</td></tr>
<tr><td>History MLP</td><td>−0.378 · P=.359</td><td>+0.024 · P=.488</td><td>−0.911 · P=.0117</td><td>0/3</td></tr>
<tr><td>Q-all</td><td>+0.048 · P=1.000</td><td>−0.357 · P=.820</td><td>+0.867 · P=.0195</td><td>1/3</td></tr>
<tr><td>Q + 选择惯性</td><td>−0.333 · P=.562</td><td>−0.333 · P=.805</td><td>+0.467 · P=.250</td><td>0/3</td></tr>
</tbody></table></div>
<p class="small"><a href="data/DA_global_temporal_model_adjudication_v4_authority.csv">冻结时间轴数据表</a>。TinyRNN 与 History MLP 提供灵活容量对照；Q-all 与选择惯性检验经典价值和持续性解释。</p>
</div></details>'''

inject("index.html",
'<div class="callout"><strong>What the original result establishes.</strong> The discriminative information comes from within-event timing. Post-outcome RPE alone is broad; the earlier sampling-policy and APE stages provide the additional mechanistic structure.</div>',
EN)

inject("index-zh.html",
'<div class="callout"><strong>先把原结论固定下来｜</strong>VTA 数据最有区分力的地方来自事件内部的时间顺序。结果后 RPE 本身并不特殊；真正增加机制信息的是更早出现的采样策略和 APE。</div>',
ZH)
