from pathlib import Path
R=Path(__file__).resolve().parents[1]
blocks={
"index.html":'''<div class="model-contract" id="slm-legacy-v179"><strong>Reconciled, not retracted: legacy SLM and DA positives.</strong> Re-running original animal-level statistics shows preceding <em>observed content</em> helps predict actual future Feed beyond mere observation recency (21/27 animals, two-sided P=.0245). The original fixed Post 0–6 s VTA DA analyses also remain positive against their own frozen baseline (Belief surprise 8/9; original one-sided P=.00586; independent two-sided P=.00781). Old and current DA tables match all nine animal-specific event counts (1,714 total); exact row-ID alignment is still an open QA item. Neither association proves a unique teaching variable, superiority to the strongest newer baseline, or a fully autonomous Feed generator. <a href="docs/SOE_SLM_VTA_LEGACY_CURRENT_RECONCILIATION_v179.md">Full source-to-source reconciliation</a> · <a href="data/SOE_VTA_v67_P_post_original_exact_reaudit_v179.csv">DA test contracts</a> · <a href="data/SOE_SLM_native_Feed_original_OOF_reaudit_v179.csv">Native Feed model ladder</a>.</div><figure class="figure evidence-figure manuscript-square" id="slm-legacy-comparison-v179"><a class="figure-zoom" href="assets/SOE_SLM_legacy_positive_independent_audit_v179.png" target="_blank" rel="noopener"><img src="assets/SOE_SLM_legacy_positive_independent_audit_v179.png" alt="Independent animals showing incremental native Feed prediction from preceding observed social content and legacy VTA Post dopamine belief surprise association" loading="lazy"/></a><figcaption><strong>Two separable positive endpoints.</strong> Left, real future Feed improvement from preceding observed content over observation recency; right, old belief-surprise prediction improvement for frozen Post DA against its original baseline. Each dot represents one independent held-out animal. These are different estimands and should not be used as a joint causal test.</figcaption></figure>''',
"index-zh.html":'''<div class="model-contract" id="slm-legacy-v179"><strong>复核结论：原先 SLM 与 DA 的正向发现应该保留，不能被不同问题的阴性结果直接覆盖。</strong> 在 27 只独立留出动物中，知道<strong>之前观察到了同伴什么行为</strong>，比只知道最近是否观察过，更能预测真实的下一次 Feed（21/27 改善，动物级双侧 P=.0245）。九只动物旧版固定 Post 0–6 秒 VTA DA 中，Belief surprise 相对原冻结基线 8/9 改善（原单侧 P=.00586；独立双侧复核 P=.00781）。旧版与新原始表的 1,714 个 Post DA 有效事件在九只动物的数量上逐一对应，逐事件 ID 仍需最后核实。以上支持正向关联，<strong>但不是已证明唯一 DA 教学规则、压倒最强基线，或完整自主进食模型已经成功</strong>。<a href="docs/SOE_SLM_VTA_LEGACY_CURRENT_RECONCILIATION_v179.md">查看完整原始结果、检验口径和新旧差异</a> · <a href="data/SOE_VTA_v67_P_post_original_exact_reaudit_v179.csv">Post DA 复算表</a> · <a href="data/SOE_SLM_native_Feed_original_OOF_reaudit_v179.csv">真实 Feed 模型增量</a>。</div><figure class="figure evidence-figure manuscript-square" id="slm-legacy-comparison-v179"><a class="figure-zoom" href="assets/SOE_SLM_legacy_positive_independent_audit_v179.png" target="_blank" rel="noopener"><img src="assets/SOE_SLM_legacy_positive_independent_audit_v179.png" alt="27 只独立动物的观察内容增量和 9 只动物结果后 DA 的旧版正向模型效应" loading="lazy"/></a><figcaption><strong>两个不同但同样重要的正向发现。</strong>左：之前观察到的社会内容，增加对真实 Feed 的留出预测力；右：旧版 Belief surprise 相对原基线，改善结果后 DA 拟合。每个点代表一只独立动物；两者不同，不能直接作为完整因果链的联合检验。</figcaption></figure>'''
}
for fn,b in blocks.items():
 p=R/fn;s=p.read_text(encoding="utf8")
 anchor='<div class="section-significance"><strong>Central contribution' if fn=="index.html" else '<div class="section-significance"><strong>核心贡献'
 assert anchor in s,(fn,anchor)
 if 'id="slm-legacy-v179"' not in s:
  s=s.replace(anchor,b+"\n"+anchor,1)
 p.write_text(s,encoding="utf8")
 print("RECONCILED_WEB",fn,s.count('id="slm-legacy-v179"'))
