from pathlib import Path
import re, html
import pandas as pd

ROOT=Path(__file__).resolve().parents[1]
DATA=ROOT/"data"
en=ROOT/"index.html"
zh=ROOT/"index-zh.html"

def behavioral_table(lang="en"):
    d=pd.read_csv(DATA/"SLM_behavior_model_comparison_canonical_v5.csv")
    d=d[pd.to_numeric(d["brier"],errors="coerce").notna()].copy()
    rows=[]
    for _,r in d.iterrows():
        group=str(r["panel_group"]).split(". ",1)[-1]
        role=str(r["main_text_role"])
        if lang=="zh":
            group={"simple behavioral baselines":"简单行为 baseline",
                   "classical low-dimensional RL":"经典低维 RL",
                   "SLM mechanistic components":"SLM 机制组件",
                   "integrated Social Learning Model":"整合 SLM",
                   "input-matched strong classical controls":"输入匹配强对照",
                   "parsimonious hybrid behavioral head":"紧凑 hybrid readout",
                   "additional flexible ceilings":"灵活容量上限",
                   "biologically inspired fixed-model baselines":"生物启发固定模型"}.get(group,group)
        rows.append(
            f"<tr><td>{html.escape(group)}</td><td>{html.escape(str(r['model']))}</td>"
            f"<td>{float(r['brier']):.4f}</td><td>{float(r['auc']):.3f}</td>"
            f"<td>{html.escape(role)}</td></tr>"
        )
    title="完整 behavioral model zoo（全部已审计行）" if lang=="zh" else "Full behavioral model zoo (all audited rows)"
    note=("RPE 不是另一种 behavioral model class；Q-learning 行通过 RPE 更新 value。真正的 RPE / policy / APE 神经信号比较在 VTA section 单独列出。"
          if lang=="zh" else
          "RPE is not a separate behavioral model class: Q-learning rows update value through an RPE. The neural comparison of RPE, policy and APE signals is listed separately in the VTA section.")
    headers=("分组","模型","Brier ↓","AUC ↑","角色") if lang=="zh" else ("Group","Model","Brier ↓","AUC ↑","Role")
    return (
      f'<details><summary>{title}</summary><div class="detail-body"><p class="small">{note}</p>'
      '<div class="table-wrap"><table class="metric-table"><thead><tr>'+
      "".join(f"<th>{h}</th>" for h in headers)+
      "</tr></thead><tbody>"+"".join(rows)+"</tbody></table></div></div></details>"
    )

def neural_table(lang="en"):
    d=pd.read_csv(DATA/"DA_global_temporal_model_adjudication_v4_authority.csv")
    rows=[]
    for _,r in d.iterrows():
        def cell(effect,p):
            if pd.isna(effect) or pd.isna(p): return "—"
            return f"{float(effect):+.3f} · P={float(p):.3g}"
        early_p=r["early_primary_p"] if "early_primary_p" in r.index else r["early_p"]
        rows.append(
            f"<tr><td>{html.escape(str(r['model_family']))}</td>"
            f"<td>{cell(r['early_effect'],early_p)}</td>"
            f"<td>{cell(r['middle_effect'],r['middle_p'])}</td>"
            f"<td>{cell(r['post_effect'],r['post_p'])}</td>"
            f"<td>{int(r['positive_sig_axes']) if pd.notna(r['positive_sig_axes']) else '—'}/3</td></tr>"
        )
    title="完整 VTA signal zoo（固定时间轴）" if lang=="zh" else "Full VTA signal zoo (fixed temporal axes)"
    headers=("候选 family","Early","Middle","Post","正且显著") if lang=="zh" else ("Candidate family","Early","Middle","Post","Positive & significant")
    note=("这里比较的是各 behavioral system 产生的候选计算信号，而不是重新比较完整 behavioral agent。"
          if lang=="zh" else
          "These are candidate computational signals generated by behavioral systems, not a second comparison of complete behavioral agents.")
    return (
      f'<details><summary>{title}</summary><div class="detail-body"><p class="small">{note}</p>'
      '<div class="table-wrap"><table class="metric-table"><thead><tr>'+
      "".join(f"<th>{h}</th>" for h in headers)+
      "</tr></thead><tbody>"+"".join(rows)+"</tbody></table></div></div></details>"
    )

EN_BLOCK=r'''
<div class="model-contract"><strong>Read the model section on three orthogonal axes.</strong> <b>Function class</b> asks whether the mapping is linear/logistic or nonlinear/recurrent. <b>Learning architecture</b> asks what state is updated: no learned state, classical value/persistence state, the structured SLM state, or a flexible world-model latent. <b>Computed signal</b> asks what variable is read at a particular moment: policy, APE, RPE or social credit. Thus “nonlinear”, “RPE” and “policy” are not alternatives at the same conceptual level.</div>
<div class="model-map">
<div class="model-family"><div class="model-tag">0 · Direct readout</div><h4>Prevalence / clock / current linear or nonlinear</h4><p><b>Principle:</b> predict choice directly from observed state; no mechanistic learning state is required.</p><p><b>Key parameters:</b> intercept, feature weights, training-fold regularization; nonlinear current-state readouts add flexible feature interactions.</p><p><b>Role:</b> establish what is predictable before introducing a learning rule.</p></div>
<div class="model-family"><div class="model-tag">1 · Classical learning rules</div><h4>RW / WSLS / Q / asymmetric-Q / forgetting-Q / choice kernel</h4><p><b>Principle:</b> maintain a few scalar values or a persistence state and update them after choices/outcomes.</p><p><b>Key parameters:</b> learning rate α; discount/value term γ where applicable; separate positive/negative α for asymmetric-Q; forgetting rate; choice-kernel decay/weight; readout scale.</p><p><b>Role:</b> interpretable reward-learning and perseveration alternatives. Q-family models generate an RPE after outcome.</p></div>
<div class="model-family"><div class="model-tag">2 · Mechanistic hypothesis</div><h4>SLM components → SLM core → default SLM</h4><p><b>Principle:</b> current state and multiscale memory determine an Observe policy; sampling generates an APE; outcome then updates source/outcome-specific social credit and value.</p><p><b>Key parameters:</b> multiscale state/decay terms, policy/readout weights, credit/value learning terms. The default behavioral SLM adds one generic choice-persistence branch.</p><p><b>Role:</b> primary mechanistic model; its coordinates are defined before VTA and JAWS tests.</p></div>
<div class="model-family"><div class="model-tag">3 · Flexible nonlinear controls</div><h4>History MLP / full-history MLP / TinyRNN h=3 / LDN</h4><p><b>Principle:</b> learn flexible nonlinear history interactions without imposing SLM semantics.</p><p><b>Key parameters:</b> hidden-layer or recurrent weights, hidden dimension, regularization and training hyperparameters selected inside training data.</p><p><b>Role:</b> capacity ceiling and stress test: does generic memory/nonlinearity explain the same behavior?</p></div>
<div class="model-family"><div class="model-tag">4 · Dynamics model</div><h4>SWM · Social World Model</h4><p><b>Principle:</b> learn a recurrent latent state that predicts future behavioral/social dynamics without supplying the SLM equations.</p><p><b>Key parameters:</b> encoder, recurrent latent dynamics and future/readout heads learned end-to-end.</p><p><b>Role:</b> test whether SLM-like coordinates emerge and whether an additional prospective social-efficacy state exists.</p></div>
</div>
<div class="model-contract"><strong>Behavioral comparison contract.</strong> The main compact comparison uses the same 27 held animals, the same event target and held-animal evaluation; Brier is the primary calibration-sensitive score, with AUC/log loss supporting. Restricted RL rows deliberately use a narrower state contract. When the claim is “SLM structure beyond the same current inputs,” the strong Current+CK / Current+Q controls reuse the current-state backbone. Flexible MLP/RNN rows are capacity ceilings, not mechanistic winners.</div>
<div class="model-contract"><strong>Terminology authority.</strong> <b>Policy</b> = the pre-outcome probability/rule for choosing Observe. <b>APE</b> = <em>actual sampling action − pre-action policy probability</em>, computed after the sampling action but before the current social outcome is available. <b>RPE</b> = a post-outcome reward/value prediction error; for Q-learning, δ = r + γV′ − V. <b>Social credit</b> = a post-outcome source/outcome-specific update. These variables can be read from different model families; they are not four competing behavioral agents.</div>
<div class="download-grid"><div class="download-card"><a href="data/SOE_MODEL_CONTRACT_REGISTRY_v1.csv">Model contract registry</a><p class="small">One-row-per-family principles, state/update rule, key parameters, role and comparison scope.</p></div></div>
''' + behavioral_table("en") + chr(10)

ZH_BLOCK=r'''
<div class="model-contract"><strong>这里必须分清三个彼此正交的维度。</strong><b>函数形式</b>问的是 linear/logistic 还是 nonlinear/recurrent；<b>学习架构</b>问的是内部更新什么状态：不学习状态、经典 value/persistence、结构化 SLM state，还是 flexible world-model latent；<b>计算信号</b>问的是某个时间点读取什么量：policy、APE、RPE 或 social credit。因此 “nonlinear”“RPE”“policy” 不属于同一层级的备选模型名。</div>
<div class="model-map">
<div class="model-family"><div class="model-tag">0 · 直接读出</div><h4>Prevalence / clock / current linear or nonlinear</h4><p><b>原理：</b>直接由可观测 current state 预测 choice，不需要机制化 learning state。</p><p><b>关键参数：</b>截距、特征权重、训练 fold 内选择的正则化；current nonlinear 额外允许灵活 feature interaction。</p><p><b>用途：</b>先建立“不加入学习规则时能预测多少”。</p></div>
<div class="model-family"><div class="model-tag">1 · 经典学习规则</div><h4>RW / WSLS / Q / asymmetric-Q / forgetting-Q / choice kernel</h4><p><b>原理：</b>维持少量 scalar value 或 persistence state，并在 choice/outcome 后更新。</p><p><b>关键参数：</b>学习率 α；需要时的 discount/value term γ；asymmetric-Q 的正/负学习率；forgetting rate；choice-kernel decay/weight；readout scale。</p><p><b>用途：</b>reward learning 与 perseveration 的可解释替代模型；Q-family 在 outcome 后产生 RPE。</p></div>
<div class="model-family"><div class="model-tag">2 · 机制假说</div><h4>SLM components → SLM core → default SLM</h4><p><b>原理：</b>current state + multiscale memory 决定 Observe policy；执行采样动作后产生 APE；outcome 出现后再更新 source/outcome-specific social credit 与 value。</p><p><b>关键参数：</b>multiscale state/decay、policy/readout weights、credit/value learning terms；default behavioral SLM 再加入一个 generic choice-persistence branch。</p><p><b>用途：</b>主要机制模型；policy、APE、credit/value 在 VTA/JAWS 之前就被定义。</p></div>
<div class="model-family"><div class="model-tag">3 · 灵活非线性对照</div><h4>History MLP / full-history MLP / TinyRNN h=3 / LDN</h4><p><b>原理：</b>不强制 SLM 语义，自由学习 nonlinear history interaction。</p><p><b>关键参数：</b>hidden-layer / recurrent weights、hidden dimension、正则化与训练超参数，都只在训练数据内选择。</p><p><b>用途：</b>容量上限与压力测试：单靠 generic memory / nonlinearity 能否解释同一行为。</p></div>
<div class="model-family"><div class="model-tag">4 · 动力学模型</div><h4>SWM · Social World Model</h4><p><b>原理：</b>不提供 SLM 方程，直接学习 recurrent latent state 去预测未来 behavioral/social dynamics。</p><p><b>关键参数：</b>encoder、recurrent latent dynamics、future/readout heads 端到端学习。</p><p><b>用途：</b>检验 SLM-like coordinates 是否自行出现，以及是否还有额外 prospective social-efficacy state。</p></div>
</div>
<div class="model-contract"><strong>行为比较 contract。</strong>主 compact comparison 固定同一批 27 只 held animals、同一 event target 与 held-animal evaluation；Brier 是主要 calibration-sensitive score，AUC/log loss 为辅助。restricted RL 故意使用更窄的 state contract；当问题变成“相同 current inputs 下 SLM structure 是否仍有价值”时，Current+CK / Current+Q 这类强对照复用 current-state backbone。MLP/RNN 是 capacity ceiling，不因为预测略强就自动获得机制解释权。</div>
<div class="model-contract"><strong>后文统一术语。</strong><b>Policy</b> = outcome 前选择 Observe 的概率/规则。<b>APE</b> = <em>actual sampling action − pre-action policy probability</em>，在采样动作发生后、当前 social outcome 可用前计算。<b>RPE</b> = outcome 后的 reward/value prediction error；Q-learning 中 δ = r + γV′ − V。<b>Social credit</b> = outcome 后、带 source/outcome 标签的更新。这些量可以由不同 model family 产生，不是四个互相竞争的 behavioral agent。</div>
<div class="download-grid"><div class="download-card"><a href="data/SOE_MODEL_CONTRACT_REGISTRY_v1.csv">Model contract registry</a><p>逐 family 列出原理、state/update rule、关键参数、用途与 comparison scope。</p></div></div>
''' + behavioral_table("zh") + chr(10)

def patch_en(s):
    s=re.sub(r'<div class="model-contract"><strong>One zoo, different contracts\.</strong>.*?(?=<div class="bio-logic"><strong>What SLM means)',
             EN_BLOCK,s,count=1,flags=re.S)
    s=s.replace("SOE_SLM_default_hierarchy_v64","SOE_SLM_default_hierarchy_v67")
    old='<figcaption><strong>Default-model hierarchy.</strong> Panel A starts from intentionally weak baselines, then classical low-dimensional learning rules, the mechanistic SLM core, the default SLM, and finally flexible capacity controls. Panel B shows the paired held-animal tests against the strongest compact and black-box controls. The full-history MLP is a ceiling audit; it no longer defines the reference frame for the SLM claim.</figcaption>'
    new='<figcaption><strong>Matched compact-model comparison.</strong> A–B show every held animal for SLM core, the strongest input-matched Current+CK compact control, and the default SLM; large symbols are mean ± SEM. C–D show the animal-level Brier and AUC gain of default SLM over Current+CK. The full audited zoo remains visible in the table below, so the main panel stays readable without hiding classical or flexible alternatives.</figcaption>'
    s=s.replace(old,new)
    s=s.replace('APE is the mismatch between the expected and observed consequence of the sampling action; RPE is reward prediction error;',
                'APE is <em>actual sampling action − pre-action policy probability</em>; RPE is the post-outcome reward/value prediction error;')
    s=s.replace("SOE_DA_temporal_logic_v65","SOE_DA_temporal_logic_v67")
    old2='<figcaption><strong>Why a single RPE explanation is incomplete.</strong> Q/RPE accounts for post-outcome DA, where reward is available. The Early sampling-policy signal and learner-linked Middle APE remain unexplained by that account. SLM is the only tested family positive and significant on all three prespecified temporal axes. Flexible TinyRNN and History MLP models achieve competitive behavior scores; their temporal neural signatures fail the same three-axis test.</figcaption>'
    new2='<figcaption><strong>Temporal neural adjudication with animal-level data.</strong> A, Early SLM-policy MSE gain for each animal and mean ± SEM. B, Middle DA–APE coupling versus SRI across animals. C, Post animal-level MSE gains for SLM RPE, Q/RPE and belief surprise; labels give directional one-sample tests of positive gain. D, the frozen Early/Middle/Post signal matrix: red = positive and P&lt;.05, gray = positive but non-significant, open = non-positive/non-significant, × = significant wrong-direction. Only SLM is positive and significant on all three prespecified axes; Q/RPE is supported at Post but not Early/Middle.</figcaption>'
    s=s.replace(old2,new2)
    # add full neural table immediately after v67 figcaption
    s=s.replace(new2+'</figure>',new2+'</figure>\n'+neural_table("en"),1)
    # normalize SWM section-head: callout becomes normal content below the head
    pat=r'(<section class="alt" id="swm"><div class="container">\s*<div class="section-head"><div><div class="section-kicker">Data-driven validation and extension</div>\s*<h2>.*?</h2></div>)\s*(<div class="callout"><strong>Why SWM is not another row in the same zoo\.</strong>.*?</div>)\s*(<p>SLM starts.*?</p>)</div>'
    m=re.search(pat,s,flags=re.S)
    if m:
        s=s[:m.start()]+m.group(1)+m.group(3)+'</div>\n'+m.group(2)+s[m.end():]
    s=s.replace('Prepublication analysis portal · authority 2026-10-05','Prepublication analysis portal · authority 2026-10-06')
    s=s.replace('Current page build: 2026-10-05','Current page build: 2026-10-06')
    return s

def patch_zh(s):
    s=re.sub(r'<div class="model-contract"><strong>同一个 model zoo，不同的检验 contract。</strong>.*?(?=<div class="bio-logic"><strong>SLM 回答什么问题)',
             ZH_BLOCK,s,count=1,flags=re.S)
    s=s.replace("SOE_SLM_default_hierarchy_v64","SOE_SLM_default_hierarchy_v67")
    old='<figcaption><strong>从弱 baseline 开始建立模型价值。</strong> Panel A 依次放入 prevalence / clock / previous choice / current state、classical RL、SLM core、default SLM 和 flexible capacity controls。Panel B 再用逐动物比较检验最强 compact / black-box controls。History MLP 只作为容量审计。</figcaption>'
    new='<figcaption><strong>输入匹配的 compact-model 比较。</strong>A–B 显示每一只 held animal 的 SLM core、最强 input-matched compact 对照 Current+CK 与 default SLM；大点为 mean ± SEM。C–D 直接显示 default SLM 相对 Current+CK 的逐动物 Brier / AUC gain。完整 audited model zoo 保留在下方表格，因此主图可以保持清楚而不隐藏经典 RL 与 flexible alternatives。</figcaption>'
    s=s.replace(old,new)
    s=s.replace('APE 表示采样动作预期结果与实际结果之间的偏差；RPE 是 reward prediction error；',
                'APE = <em>actual sampling action − pre-action policy probability</em>；RPE 是 outcome 后的 reward/value prediction error；')
    s=s.replace("SOE_DA_temporal_logic_v65","SOE_DA_temporal_logic_v67")
    old2='<figcaption><strong>为什么单一 RPE 解释不够。</strong> Q/RPE 可以解释 post-outcome DA；Early sampling policy 与 learner-linked Middle APE 出现在 outcome 之前，Q/RPE 无法覆盖这两个时间窗。SLM 是当前候选中唯一在三个 prespecified temporal axes 上都为正且显著的 family。TinyRNN 与 History MLP 在行为预测上有竞争力，但没有复现相同的 neural sequence。</figcaption>'
    new2='<figcaption><strong>用逐动物数据做时间判别。</strong>A，逐动物 Early SLM-policy MSE gain 与 mean ± SEM。B，Middle DA–APE coupling 与 SRI 的动物间关系。C，逐动物 Post MSE gain，比较 SLM RPE、Q/RPE 与 belief surprise；标注为 gain&gt;0 的方向性 one-sample test。D，冻结的 Early/Middle/Post signal matrix：红实心 = 正且 P&lt;.05，灰实心 = 正但不显著，空心 = 非正/不显著，× = 显著反方向。当前只有 SLM 在三个 prespecified axes 上都为正且显著；Q/RPE 只在 Post 得到支持。</figcaption>'
    s=s.replace(old2,new2)
    s=s.replace(new2+'</figure>',new2+'</figure>\n'+neural_table("zh"),1)
    # repair SWM malformed p/div and move callout after section head
    pat=r'(<section class="alt" id="swm"><div class="container">\s*<div class="section-head"><div><div class="section-kicker">数据驱动的独立验证与扩展</div>\s*<h2>.*?</h2></div>)\s*<p>(<div class="callout"><strong>为什么 SWM 不直接作为同一个 model zoo 的又一行。</strong>.*?</div>)(SLM 从.*?</p>)</div>'
    m=re.search(pat,s,flags=re.S)
    if m:
        para=m.group(3)
        s=s[:m.start()]+m.group(1)+'<p>'+para+'</div>\n'+m.group(2)+s[m.end():]
    s=s.replace('，，','，')
    s=s.replace('中文机制版 · authority 2026-10-05','中文机制版 · authority 2026-10-06')
    s=s.replace('Current page build: 2026-10-05','Current page build: 2026-10-06')
    return s

for path,fn in [(en,patch_en),(zh,patch_zh)]:
    s=path.read_text(encoding="utf-8")
    out=fn(s)
    if out==s:
        raise RuntimeError(f"No changes applied to {path.name}")
    path.write_text(out,encoding="utf-8")
    print(path.name, "patched", len(s), "->", len(out))
